spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://localhost:9296
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092

    gateway:
      routes:
        - id: auth-service-app
          uri: lb://AUTHSERVICEAPP
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: propertyservice-api
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/property/**
          filters:
            - RewritePath=/property/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: propertyServiceCircuitBreaker
                fallbackUri: forward:/fallback/property
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

zipkin:
  base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

