spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://localhost:9296

    bus:
      enabled: true
      kafka:
        consumer:
          # CRITICAL FIX 1: Provide the default class type for bus events when headers are missing.
          properties:
            spring.json.value.default.type: org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent
          # CRITICAL FIX 2: Set to latest to skip corrupted messages when starting fresh
          auto-offset-reset: latest 

    stream:
      # CRITICAL FIX 3: Define a fixed group ID for the bus topic to prevent anonymous IDs
      bindings:
        springCloudBusInput:
          group: ${spring.application.name} # Will resolve to 'api-gateway'
      kafka:
        binder:
          brokers: localhost:9092

    gateway:
      routes:
        - id: auth-service-app
          uri: lb://AUTHSERVICEAPP
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: propertyservice-api
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/property/**
          filters:
            - RewritePath=/property/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: propertyServiceCircuitBreaker
                fallbackUri: forward:/fallback/property
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
    
  # *** NEW SECTION FOR ERROR HANDLING DESERIALIZER ***
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # CRITICAL FIX 4: Use the ErrorHandlingDeserializer to catch serialization errors
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        # CRITICAL FIX 5: Delegate the actual deserialization to the original classes
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  # *** END OF NEW SECTION ***

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

zipkin:
  base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
