spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://localhost:9296

    bus:
      enabled: true
      id: ${spring.application.name}
      kafka:
        consumer:
          properties:
            spring.json.value.default.type: org.springframework.cloud.bus.event.RemoteApplicationEvent

  gateway:
    routes:
      - id: auth-service-app
        uri: lb://AUTHSERVICEAPP
        predicates:
          - Path=/auth/**
        filters:
          - RewritePath=/auth/(?<segment>.*), /${segment}

      - id: propertyservice-api
        uri: lb://PROPERTY-SERVICE
        predicates:
          - Path=/property/**
        filters:
          - RewritePath=/property/(?<segment>.*), /${segment}
          - name: CircuitBreaker
            args:
              name: propertyServiceCircuitBreaker
              fallbackUri: forward:/fallback/property
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: org.springframework.cloud.bus.event.RemoteApplicationEvent

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

zipkin:
  base-url: http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
