spring:
  application:
    name: property-service
    
  # --- 1. SPRING CLOUD BUS & KAFKA STREAM BINDER ---
  # This section enables the service to listen for bus-refresh events on Kafka.
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          # IMPORTANT: Use the same bootstrap-servers as your main Kafka config
          # The property-service must connect to the bus/stream broker.
          brokers: ec2-13-127-137-128.ap-south-1.compute.amazonaws.com:9092
  
  # --- 2. DATASOURCE CONFIGURATION ---
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/propertydb_m
    username: root
    password: test
  
  # --- 3. JPA/HIBERNATE CONFIGURATION ---
  jpa:
    hibernate:
      ddl-auto: update
      
  # --- 4. SERVLET/MULTIPART CONFIGURATION ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      
  # --- 5. APPLICATION-SPECIFIC KAFKA CONFIGURATION ---
  kafka:
    bootstrap-servers: ec2-13-127-137-128.ap-south-1.compute.amazonaws.com:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      properties:
        num.partitions: 1
        replication.factor: 1
        
  # --- 6. MAIN CONFIGURATION ---
  main:
    allow-circular-references: true
    
# --- 7. ACTUATOR ENDPOINT EXPOSURE ---
# This is necessary for the service to process the refresh event internally.
management:
  endpoints:
    web:
      exposure:
        # Expose the 'refresh' endpoint so the service can process the config change
        include: "health,info,refresh"
        # If you were refreshing the property-service itself, you'd add: bus-refresh

# --- 8. APPLICATION PROPERTIES ---
product:
  message: Configuration Updated Successfully!
