spring:
  application:
    name: property-service

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/propertydb_m
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update

aws:
  s3:
    bucket-name: hms-photos-3
  region:
    static: ap-south-1
  credentials:
    access-key: AKIAZKDIDF7GRNFCZ45U
    secret-key: 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

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

spring:
  kafka:
    bootstrap-servers: ec2-13-127-137-128.ap-south-1.compute.amazonaws.com:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      properties:
        num.partitions: 1
        replication.factor: 1

spring:
  main:
    allow-circular-references: true
