spring:
  application:
    name: property-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/propertydb_dev
    username: root
    password: test

server:
  port: 9091   # Different from default

aws:
  s3:
    bucket-name: hms-photos-dev
