spring:
  application:
    name: property-service

  # --- 1. SPRING CLOUD BUS & KAFKA STREAM BINDER (DLQ FIX) ---
  cloud:
    bus:
      enabled: true
      kafka:
        consumer:
          # CRITICAL FIX 1: Default type when headers missing
          properties:
            spring.json.value.default.type: org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent
          auto-offset-reset: latest

    stream:
      # CRITICAL FIX 2: Fixed group ID so no random anonymous IDs
      bindings:
        springCloudBusInput:
          group: ${spring.application.name} # property-service
          # CRITICAL FIX 3: DLQ enabled so corrupted messages NEVER get retried forever
          consumer:
            max-attempts: 1
            enable-dlq: true
      kafka:
        binder:
          brokers: localhost:9092

  # --- 2. DATASOURCE CONFIGURATION ---
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/propertydb_m
    username: root
    password: test

  # --- 3. JPA/HIBERNATE CONFIGURATION ---
  jpa:
    hibernate:
      ddl-auto: update

  # --- 4. SERVLET/MULTIPART CONFIG ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  # --- 5. APPLICATION-SPECIFIC KAFKA (ErrorHandlingDeserializer) ---
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group
      auto-offset-reset: latest

      # CRITICAL FIX — use ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.json.trusted.packages: "*"

        # Delegate actual deserialization
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      properties:
        num.partitions: 1
        replication.factor: 1

  # --- 6. MAIN CONFIG ---
  main:
    allow-circular-references: true


# --- 7. ACTUATOR ---
management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"

# --- 8. APPLICATION-SPECIFIC PROPS ---
product:
  message: Updated Successfully
