spring:
  application:
    name: property-service
    
  # --- 1. SPRING CLOUD BUS & KAFKA STREAM BINDER ---
  cloud:
    bus:
      enabled: true
      # 👇 CRITICAL FIX: Tell the Spring Cloud Bus consumer to start from the latest offset 
      #    to skip any corrupted historical messages on the 'springCloudBus' topic.
      kafka:
        consumer:
          auto-offset-reset: latest 
          
    stream:
      kafka:
        binder:
          # IMPORTANT: Use the same bootstrap-servers as your main Kafka config
          # The property-service must connect to the bus/stream broker.
          brokers: localhost:9092
          
  # --- 2. DATASOURCE CONFIGURATION ---
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/propertydb_m
    username: root
    password: test
    
  # --- 3. JPA/HIBERNATE CONFIGURATION ---
  jpa:
    hibernate:
      ddl-auto: update
      
  # --- 4. SERVLET/MULTIPART CONFIGURATION ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      
  # --- 5. APPLICATION-SPECIFIC KAFKA CONFIGURATION ---
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest # This is for your application's custom consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      properties:
        num.partitions: 1
        replication.factor: 1
        
  # --- 6. MAIN CONFIGURATION ---
  main:
    allow-circular-references: true
    
# --- 7. ACTUATOR ENDPOINT EXPOSURE ---
management:
  endpoints:
    web:
      exposure:
        # Expose the 'refresh' endpoint so the service can process the config change
        include: "health,info,refresh"
        
# --- 8. APPLICATION PROPERTIES ---
product:
  message: Updated Successfully!
