spring:
  application:
    name: property-service

  # --- 1. SPRING CLOUD BUS & KAFKA STREAM BINDER ---
  cloud:
    bus:
      enabled: true
      kafka:
        consumer:
          # CRITICAL FIX 1: Provide the default class type for bus events when headers are missing.
          properties:
            spring.json.value.default.type: org.springframework.cloud.bus.event.RefreshRemoteApplicationEvent
          # Keep this in case a new group is created:
          auto-offset-reset: latest

    stream:
      # CRITICAL FIX 2: Define a fixed group ID for the bus topic to prevent anonymous IDs
      bindings:
        springCloudBusInput:
          group: ${spring.application.name} # Will resolve to 'property-service'
      kafka:
        binder:
          # IMPORTANT: Use the same bootstrap-servers as your main Kafka config
          brokers: localhost:9092

  # --- 2. DATASOURCE CONFIGURATION ---
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/propertydb_m
    username: root
    password: test

  # --- 3. JPA/HIBERNATE CONFIGURATION ---
  jpa:
    hibernate:
      ddl-auto: update

  # --- 4. SERVLET/MULTIPART CONFIGURATION ---
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  # --- 5. APPLICATION-SPECIFIC KAFKA CONFIGURATION ---
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest # This is for your application's custom consumers
      
      # *** CRITICAL FIX: Use the ErrorHandlingDeserializer to catch serialization errors ***
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      
      properties:
        spring.json.trusted.packages: "*"
        
        # *** CRITICAL FIX: Delegate the actual deserialization to the original classes ***
        # Tells the ErrorHandlingDeserializer what to use for the key
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        # Tells the ErrorHandlingDeserializer what to use for the value
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      properties:
        num.partitions: 1
        replication.factor: 1

  # --- 6. MAIN CONFIGURATION ---
  main:
    allow-circular-references: true

# --- 7. ACTUATOR ENDPOINT EXPOSURE ---
management:
  endpoints:
    web:
      exposure:
        # Expose the 'refresh' endpoint so the service can process the config change
        include: "health,info,refresh"

# --- 8. APPLICATION PROPERTIES ---
product:
  message:  Updated Successfully
